Tin 2
a40o/Tinder pull request #7
Opened 2024-01-09 13:37 UTC by a40o

2024-01-09 17:59 UTC, todornikolov1 requested changes

2024-01-09 17:59 UTC, todornikolov1 commented on src/main/java/com/volasoftware/tinder/jwt/JwtAuthenticationFilter.java
> +    private static final String BEARAR_PREFIX = "Bearer ";
Probable typo in BEARAR?

2024-01-09 17:59 UTC, todornikolov1 commented on src/main/java/com/volasoftware/tinder/jwt/JwtGenerator.java
> +    private static final long EXPIRATION_TIME =604800000L;
```suggestion
    private static final long EXPIRATION_TIME = 604800000L;
```
How long is that?
Is it normal to be same value to each environment?

2024-01-09 17:59 UTC, todornikolov1 commented on src/main/java/com/volasoftware/tinder/jwt/JwtGenerator.java
> +
remove the empty line

2024-01-09 17:59 UTC, todornikolov1 commented on src/main/java/com/volasoftware/tinder/jwt/JwtServiceImpl.java
> +
remove the line

2024-01-09 17:59 UTC, todornikolov1 commented on src/main/java/com/volasoftware/tinder/services/UserService.java
> +    public UserDetailsService userDetailsService() {
method name should be verb

2024-01-09 17:59 UTC, todornikolov1 commented on src/main/resources/db/migration/V001__Create_user_table.sql
> +    PASSWORD varchar(255) not null,
create a new migration,  alter the table and change the field max length there

2024-01-09 17:59 UTC, todornikolov1 commented on src/main/resources/db/migration/V004__Add_role_column.sql
> +ADD COLUMN ROLE varchar(15) not null AFTER GENDER;
15 is not a big number for a word that can be a role name some day. Think for the future use, not the current need

2024-01-10 08:00 UTC, Kr1s4an commented on src/main/java/com/volasoftware/tinder/jwt/JwtAuthenticationFilter.java
> +    protected void doFilterInternal(@NotNull HttpServletRequest request,
Separate methods

2024-01-11 11:15 UTC, todornikolov1 commented on src/main/resources/db/migration/V006__Change_role_field_length.sql
> +ALTER TABLE user MODIFY COLUMN ROLE varchar (50) not null;
It's no problem to create a single migration file and add all changes in it (no need every change to be in a separate migration)

2024-01-11 11:15 UTC, todornikolov1 commented on src/main/resources/db/migration/V004__Add_role_column.sql
> +ADD COLUMN ROLE varchar(15) not null AFTER GENDER;
You should set default value for role, as you're defining it as not nullable
Because it's a new migration, just change 15 to 50, that's all.

2024-01-15 09:03 UTC, merged